# Generated by Django 5.1.7 on 2025-04-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_estoque_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.medicamento', unique=True),
        ),
    ]
